const audioDrum = [{keycode: 69,
                    key:"E",
                    id:"crashCymbal",
                    url:"https://github.com/arthurlee945/AudioLibrary/blob/main/Drum/crash_cymbol.mp3?raw=true"},
                    {keycode: 82,
                      key:"R",
                      id:"highTom",
                      url:"https://github.com/arthurlee945/AudioLibrary/blob/main/Drum/tom_high.mp3?raw=true"},
                    {keycode: 85,
                      key:"U",
                      id:"midTom",
                      url:"https://github.com/arthurlee945/AudioLibrary/blob/main/Drum/tom_mid.mp3?raw=true"},
                    {keycode: 73,
                      key:"I",
                      id:"rideCymbal",
                      url:"https://github.com/arthurlee945/AudioLibrary/blob/main/Drum/ride_bow.mp3?raw=true"},
                    {keycode: 65,
                      key:"A",
                      id:"hatOpen",
                      url:"https://github.com/arthurlee945/AudioLibrary/blob/main/Drum/hat_open.mp3?raw=true"},
                    {keycode: 70,
                      key:"F",
                      id:"snareDrum",
                      url:"https://github.com/arthurlee945/AudioLibrary/blob/main/Drum/snare_drum.mp3?raw=true"},
                    {keycode: 32,
                      key:"Space",
                      id:"bassDrum",
                      url:"https://github.com/arthurlee945/AudioLibrary/blob/main/Drum/bass.mp3?raw=true"},
                    {keycode: 76,
                      key:"L",
                      id:"floorTom",
                      url:"https://github.com/arthurlee945/AudioLibrary/blob/main/Drum/tom_floor.mp3?raw=true"},

                    {keycode: 16,
                      key:"Shift",
                      id:"hatClosed",
                      url:"https://github.com/arthurlee945/AudioLibrary/blob/main/Drum/hat_closed.mp3?raw=true"}];
const audioTri = [{keycode: 84,
                    key:"T",
                    id:"triangle",
                    url:"https://github.com/arthurlee945/AudioLibrary/blob/main/Triangle/triangle.mp3?raw=true"},
                  {keycode: 75,
                    key:"K",
                    id:"triangle_V2",
                    url:"https://github.com/arthurlee945/AudioLibrary/blob/main/Triangle/triangle%20v2.mp3?raw=true"},
                  {keycode: 32,
                    key:"Space",
                    id:"muffle",
                    url:"https://github.com/arthurlee945/AudioLibrary/blob/main/Triangle/Triangle%20muffled.mp3?raw=true"}   
                  ]


export {audioDrum, audioTri};